### ISSUE TITLE
Code not working correctly on python 3.9

### ISSUE THREAD

**Issue by HamzLDN** [anapeksha/python-proxy-server#7]
python3 src/server.py --max_conn=10 --buffer_size=8192
Traceback (most recent call last):
  File "/home/bluepill/python-proxy-server/src/server.py", line 9, in <module>
    listening_port = config('PORT', cast=int)
  File "/home/bluepill/.local/lib/python3.9/site-packages/decouple.py", line 248, in __call__
    return self.config(*args, **kwargs)
  File "/home/bluepill/.local/lib/python3.9/site-packages/decouple.py", line 107, in __call__
    return self.get(*args, **kwargs)
  File "/home/bluepill/.local/lib/python3.9/site-packages/decouple.py", line 92, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: PORT not found. Declare it as envvar or define a default value.

I've installed the requirements:
python-decouple

I'm running it on Linux (Debian). I have opened the required ports. But I still have this issue.
Thanks for your time

**Comment by ShailMurtaza** [comment]
@HamzLDN 

At line 9 don't use decouple. Try to hard code port number of your choice manually. Also do not import decouple as it is only used while in docker Virtual environment.

**Comment by senkron24** [comment]
> @HamzLDN
> 
> At line 9 don't use decouple. Try to hard code port number of your choice manually. Also do not import decouple as it is only used while in docker Virtual environment.

export PORT=8080  # Set the desired port number
python3 proxy.py --max_conn=10 --buffer_size=8192


its working with this bud not any site opened on the clint just get timeout

**Comment by anapeksha** [comment]
Kindly raise PR for supporting this project.

**Comment by HamzLDN** [comment]
Thank you
