### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by nethomas1968** [anapeksha/python-proxy-server#8]
I don't understand the testing instructions:

If running the proxy on your local machine with the above example, point your proxy to; localhost 8000
Test access to a HTTP only webpage such as; http://neverssl.com

What commands are used to "point your proxy" ???

**Comment by ShailMurtaza** [comment]
@nethomas1968 
You need to run proxy server on one machine. On otter machine you will have to connect proxy server by setting up your OS or browser.

Then in that other machine you can open any HTTP website and it OS/Browser (whatever you configured to use proxy) will pass all your data to your proxy server.

Firefox has builtin feature for using proxy server. You will have to install some extension in chrome. Or you can configure your Operating system
